# Generated by Django 5.2.12 on 2026-03-10 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedistributionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hospital', models.CharField(max_length=120)),
                ('target_hospital', models.CharField(max_length=120)),
                ('blood_group', models.CharField(max_length=5)),
                ('suggested_units', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redistributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('component_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('packed_rbc', 'Packed RBCs'), ('platelets', 'Platelets'), ('ffp', 'Fresh Frozen Plasma')], default='whole_blood', max_length=20)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=12)),
                ('hospital_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units', to='donations_app.donation')),
            ],
            options={
                'indexes': [models.Index(fields=['blood_group', 'status'], name='donations_a_blood_g_5a2bb5_idx'), models.Index(fields=['expiry_date'], name='donations_a_expiry__912267_idx'), models.Index(fields=['hospital_name'], name='donations_a_hospita_52b521_idx')],
            },
        ),
    ]
