# Generated by Django 5.2.12 on 2026-03-10 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations_app', '0002_redistributionsuggestion_bloodunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organ_type', models.CharField(choices=[('kidney', 'Kidney'), ('liver', 'Liver'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('pancreas', 'Pancreas'), ('corneas', 'Corneas'), ('small_intestine', 'Small Intestine'), ('bone_marrow', 'Bone Marrow')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('collection_datetime', models.DateTimeField()),
                ('expiry_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('transplanted', 'Transplanted'), ('discarded', 'Discarded'), ('expired', 'Expired')], default='available', max_length=12)),
                ('hospital_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_units', to='donations_app.donation')),
            ],
            options={
                'indexes': [models.Index(fields=['organ_type', 'status'], name='donations_a_organ_t_f1d760_idx'), models.Index(fields=['expiry_datetime'], name='donations_a_expiry__892f74_idx'), models.Index(fields=['hospital_name'], name='donations_a_hospita_863a12_idx')],
            },
        ),
    ]
