# Generated by Django 5.0.6 on 2026-02-25 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('MATCH_ALERT', 'Match Alert'), ('REQUEST_UPDATE', 'Request Update'), ('VERIFY_STATUS', 'Verification Status')], max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_861df1_idx'), models.Index(fields=['type'], name='notificatio_type_ec685f_idx'), models.Index(fields=['created_at'], name='notificatio_created_ca1755_idx')],
            },
        ),
    ]
