# Generated by Django 5.2.12 on 2026-03-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='requests_app.request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH_ALERT', 'Match Alert'), ('REQUEST_UPDATE', 'Request Update'), ('VERIFY_STATUS', 'Verification Status'), ('SOS_ALERT', 'SOS Alert'), ('SOS_RESPONSE', 'SOS Response'), ('COOLDOWN_REMINDER', 'Cooldown Reminder'), ('MILESTONE', 'Milestone'), ('IMPACT', 'Impact'), ('ESCALATION', 'Escalation')], max_length=40),
        ),
    ]
