# Generated by Django 5.0.6 on 2026-02-25 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('organ_willing', models.BooleanField(default=False)),
                ('organ_types', models.JSONField(blank=True, default=list)),
                ('last_blood_donation_date', models.DateField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blood_group'], name='donors_dono_blood_g_0b5c5a_idx'), models.Index(fields=['city'], name='donors_dono_city_660947_idx'), models.Index(fields=['verification_status'], name='donors_dono_verific_61ca1a_idx'), models.Index(fields=['availability_status'], name='donors_dono_availab_8bb9b8_idx')],
            },
        ),
    ]
