# Generated by Django 5.2.12 on 2026-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='donation_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donation_type',
            field=models.CharField(blank=True, choices=[('whole_blood', 'Whole Blood'), ('power_red', 'Power Red'), ('platelets', 'Platelets'), ('plasma', 'Plasma')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_streak_quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
