# Generated by Django 5.0.6 on 2026-02-25 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('BLOOD', 'Blood'), ('ORGAN', 'Organ')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('organ_type', models.CharField(blank=True, max_length=80, null=True)),
                ('units_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MATCHING', 'Matching'), ('MATCHED', 'Matched'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='hospitals.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='requests_ap_status_9b7335_idx'), models.Index(fields=['request_type'], name='requests_ap_request_7e451f_idx'), models.Index(fields=['urgency'], name='requests_ap_urgency_758967_idx'), models.Index(fields=['city'], name='requests_ap_city_0f4d6b_idx'), models.Index(fields=['created_by'], name='requests_ap_created_23a307_idx')],
            },
        ),
    ]
