# Generated by Django 5.2.12 on 2026-03-10 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_address_line_1_hospital_address_line_2_and_more'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='original_urgency',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='priority_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['-priority_score'], name='requests_ap_priorit_6a911a_idx'),
        ),
    ]
