# Generated by Django 5.0.6 on 2026-02-25 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('donor_response', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='requests_app.request')),
            ],
            options={
                'indexes': [models.Index(fields=['request'], name='matching_ma_request_cfdc18_idx'), models.Index(fields=['donor_user'], name='matching_ma_donor_u_5d6ec8_idx'), models.Index(fields=['donor_response'], name='matching_ma_donor_r_1256a8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('request', 'donor_user'), name='unique_request_donor_match'),
        ),
    ]
